### ISSUE TITLE
Cannot find file after cloning repo

### ISSUE THREAD

**Issue by bayismet** [Whadup/weightedFastText#2]
Hello there!

Yesterday, I cloned this repo again, in order to start from scratch. But right now, I encountered another issue, as following:
![Cannot find a module](https://user-images.githubusercontent.com/28671373/119458444-6df38100-bd45-11eb-8067-185d8dca913f.png)
Thanks!

**Comment by Whadup** [comment]
did you use `pip install . `to install this repo?

**Comment by bayismet** [comment]
Yea, that solved the problem!
